/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bol.view;

import com.bol.services.impl.Channel;
import java.awt.Color;

/**
 *
 * @author USER
 */
public class ChannelView extends javax.swing.JFrame {

    /**
     * Creates new form Channel
     */
    public ChannelView() {
        initComponents();        
        redStartLbl1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        mainPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        subsChannelLbl1 = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        greenStartLbl = new javax.swing.JLabel();
        redStartLbl1 = new javax.swing.JLabel();
        startChannelLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        channelLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        mainLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mainPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 20, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        mainPnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 20, 20));
        mainPnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 550, -1));

        subsChannelLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        subsChannelLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subsChannelLbl1.setText("Start Channel");
        subsChannelLbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        subsChannelLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subsChannelLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subsChannelLbl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subsChannelLbl1MouseExited(evt);
            }
        });
        mainPnl.add(subsChannelLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 180, 30));

        userLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        mainPnl.add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 240, 270));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Name :");
        mainPnl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 20));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Enter Channel Name");
        mainPnl.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 30));

        greenStartLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greenStartLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bol/assets/start_24px.png"))); // NOI18N
        mainPnl.add(greenStartLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 30, 30));

        redStartLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redStartLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bol/assets/start_24px_red.png"))); // NOI18N
        mainPnl.add(redStartLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 30, 30));

        startChannelLbl.setBackground(new java.awt.Color(0, 0, 204));
        startChannelLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        startChannelLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startChannelLbl.setText("Start Channel");
        startChannelLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        startChannelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startChannelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startChannelLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startChannelLblMouseExited(evt);
            }
        });
        mainPnl.add(startChannelLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 180, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Start Channel");
        mainPnl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 180, 30));

        channelLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        channelLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Channel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(1, 0, 0))); // NOI18N
        mainPnl.add(channelLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, 270));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainPnl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 10, 310));

        mainLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bol/assets/TyOgzR.png"))); // NOI18N
        mainPnl.add(mainLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startChannelLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startChannelLblMouseEntered
        redStartLbl1.setVisible(true);
        greenStartLbl.setVisible(false);
        startChannelLbl.setBackground(Color.red);
        startChannelLbl.setOpaque(true);// TODO add your handling code here:
    }//GEN-LAST:event_startChannelLblMouseEntered

    private void startChannelLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startChannelLblMouseExited
        redStartLbl1.setVisible(false);
        greenStartLbl.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_startChannelLblMouseExited

    private void subsChannelLbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsChannelLbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_subsChannelLbl1MouseEntered

    private void subsChannelLbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsChannelLbl1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_subsChannelLbl1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChannelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChannelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChannelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChannelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChannelView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel channelLbl;
    private javax.swing.JLabel greenStartLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mainLbl;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JLabel redStartLbl1;
    private javax.swing.JLabel startChannelLbl;
    private javax.swing.JLabel subsChannelLbl1;
    private javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables
}
