/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bol.view;

import com.bol.services.impl.Channel;


public class HomeView extends javax.swing.JFrame {

    private Channel channel;
    
    public HomeView() {
        initComponents();
        subscribeBtn.setVisible(false);
        channelLabl.setVisible(false);
    }
    
    public HomeView(Channel c) {
        this();
        this.channel = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        channelLabl = new javax.swing.JLabel();
        startChannelBtn = new javax.swing.JButton();
        startChannelTxt = new javax.swing.JTextField();
        subscribeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(channelLabl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 20));

        startChannelBtn.setText("Start Channel");
        startChannelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startChannelBtnMouseClicked(evt);
            }
        });
        startChannelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startChannelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(startChannelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));
        jPanel1.add(startChannelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        subscribeBtn.setText("subscribe");
        subscribeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(subscribeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel1.setText("No channels avaliable yet");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel2.setText("Channel Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeBtnActionPerformed
        UserView user = new UserView(channelLabl.getText());
        this.channel.subscribeChannel(channelLabl.getText(),user);
        user.setVisible(true);
    }//GEN-LAST:event_subscribeBtnActionPerformed

    private void startChannelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startChannelBtnMouseClicked
        this.channel.addChannel(startChannelTxt.getText());
        jLabel1.setVisible(false);
        channelLabl.setText(startChannelTxt.getText());
        startChannelBtn.setEnabled(false);
        subscribeBtn.setVisible(true);
        channelLabl.setVisible(true);
        new NewChannelView(startChannelTxt.getText()).setVisible(true);
    }//GEN-LAST:event_startChannelBtnMouseClicked

    private void startChannelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startChannelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startChannelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel channelLabl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton startChannelBtn;
    private javax.swing.JTextField startChannelTxt;
    private javax.swing.JButton subscribeBtn;
    // End of variables declaration//GEN-END:variables
}
