/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bol.view;

import com.bol.services.impl.QuoteChannel;
import com.bol.controller.ChannelController;


public class NewChannelView extends javax.swing.JFrame{
    
    private QuoteChannel quoteChannel = QuoteChannel.getInstance();
    private ChannelController channelController = new ChannelController();
    
    public NewChannelView() {
        initComponents();
        ChannelNameLbl.setText(quoteChannel.name);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        mainMsg = new javax.swing.JTextField();
        shareBtn = new javax.swing.JButton();
        ChannelNameLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMsg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mainPnl.add(mainMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 128, 372, 110));

        shareBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        shareBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bol/assets/share_squared_30px.png"))); // NOI18N
        shareBtn.setText("SHARE");
        shareBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareBtnActionPerformed(evt);
            }
        });
        mainPnl.add(shareBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 256, 120, 30));

        ChannelNameLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ChannelNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChannelNameLbl.setAlignmentX(0.5F);
        ChannelNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainPnl.add(ChannelNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 308, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        mainPnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 5, 20, 20));
        mainPnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 400, 20));

        mainLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bol/assets/bd.jpg"))); // NOI18N
        mainPnl.add(mainLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(mainPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareBtnActionPerformed
        this.channelController.notifySubcribers(quoteChannel, mainMsg.getText());
    }//GEN-LAST:event_shareBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChannelNameLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainLbl;
    private javax.swing.JTextField mainMsg;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JButton shareBtn;
    // End of variables declaration//GEN-END:variables

}
