/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bol.view;

import com.bol.services.impl.Channel;

/**
 *
 * @author USER
 */
public class one extends javax.swing.JFrame {

    /**
     * Creates new form one
     */
    
    private Channel channel = new Channel();
    
    public one() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxtfield = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        channelLabl = new javax.swing.JLabel();
        subscribeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nameTxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 46, 91, 34));

        startBtn.setText("Start");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });
        getContentPane().add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 119, -1, -1));

        jLabel1.setText("No channels");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 55, -1, -1));
        getContentPane().add(channelLabl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 119, -1, -1));

        subscribeBtn.setText("subscribe");
        subscribeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(subscribeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 119, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeBtnActionPerformed
        three u1 = new three(channelLabl.getText());
        channel.subscribeChannel(channelLabl.getText(),u1);
        u1.setVisible(true);
    }//GEN-LAST:event_subscribeBtnActionPerformed

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        channel.addChannel(nameTxtfield.getText());
        jLabel1.setVisible(false);
        channelLabl.setText(nameTxtfield.getText());
        startBtn.setEnabled(false);
        new two(channel).setVisible(true);
    }//GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new one().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel channelLabl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTxtfield;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton subscribeBtn;
    // End of variables declaration//GEN-END:variables
}
